require('dotenv').config();
const { sequelize } = require('../config/database');
const {
  User,
  Business,
  Event,
  EventAttendee,
  ChatRoom,
  ChatMember,
  Follow,
  Notification,
  SavedEvent,
  Review,
} = require('../models');
const logger = require('../utils/logger');

const seed = async () => {
  try {
    logger.info('Starting database seed...');

    await sequelize.sync({ force: true });
    logger.info('Database tables created.');

    // ===== Create Users =====
    const users = await User.bulkCreate([
      {
        username: 'sarah_chen',
        email: 'sarah@example.com',
        password_hash: 'password123',
        display_name: 'Sarah Chen',
        bio: 'Coffee lover, trivia enthusiast, and always looking for the next adventure. New to the city and ready to explore!',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2672,
        longitude: -97.7431,
        interests: ['trivia', 'coffee', 'board_games', 'hiking', 'live_music'],
        account_type: 'user',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'mike_rodriguez',
        email: 'mike@example.com',
        password_hash: 'password123',
        display_name: 'Mike Rodriguez',
        bio: 'Fitness junkie and foodie. Love trying new restaurants and hitting the gym. Always down for a good time!',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2750,
        longitude: -97.7400,
        interests: ['fitness', 'food', 'sports', 'happy_hour', 'comedy'],
        account_type: 'user',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'emma_wilson',
        email: 'emma@example.com',
        password_hash: 'password123',
        display_name: 'Emma Wilson',
        bio: 'Artist, yoga lover, and craft beer enthusiast. Looking for creative events and chill vibes.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2600,
        longitude: -97.7500,
        interests: ['art', 'yoga', 'craft_beer', 'music', 'painting'],
        account_type: 'user',
        is_verified: false,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'james_park',
        email: 'james@example.com',
        password_hash: 'password123',
        display_name: 'James Park',
        bio: 'Tech professional by day, board game geek by night. Always up for meeting new people over games.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2800,
        longitude: -97.7350,
        interests: ['board_games', 'tech', 'trivia', 'escape_rooms', 'coffee'],
        account_type: 'user',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'luna_martinez',
        email: 'luna@example.com',
        password_hash: 'password123',
        display_name: 'Luna Martinez',
        bio: 'Dance teacher and salsa lover. Life is too short to sit still! Come dance with me.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2550,
        longitude: -97.7600,
        interests: ['dance', 'salsa', 'music', 'cooking', 'festivals'],
        account_type: 'user',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'brewhaus_atx',
        email: 'brewhaus@example.com',
        password_hash: 'password123',
        display_name: 'BrewHaus ATX',
        bio: "Austin's favorite craft brewery and taproom. 24 taps, great food, and even better vibes.",
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2672,
        longitude: -97.7431,
        interests: ['craft_beer', 'live_music', 'food', 'community'],
        account_type: 'business',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'grindhouse_coffee',
        email: 'grindhouse@example.com',
        password_hash: 'password123',
        display_name: 'Grindhouse Coffee',
        bio: 'Specialty coffee shop and coworking space. The best beans in Austin, period.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2700,
        longitude: -97.7380,
        interests: ['coffee', 'coworking', 'art', 'community'],
        account_type: 'business',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'lucky_lanes',
        email: 'luckylanes@example.com',
        password_hash: 'password123',
        display_name: 'Lucky Lanes Bowling',
        bio: 'Retro bowling alley with a modern twist. Glow bowling, arcade, great drinks, and amazing events!',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2630,
        longitude: -97.7520,
        interests: ['bowling', 'arcade', 'entertainment', 'food'],
        account_type: 'business',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'flow_yoga',
        email: 'flowyoga@example.com',
        password_hash: 'password123',
        display_name: 'Flow Yoga Studio',
        bio: 'Find your flow. Community-centered yoga studio offering classes for all levels.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2580,
        longitude: -97.7450,
        interests: ['yoga', 'wellness', 'meditation', 'community'],
        account_type: 'business',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'palette_gallery',
        email: 'palette@example.com',
        password_hash: 'password123',
        display_name: 'Palette Art Gallery',
        bio: 'Contemporary art gallery and creative space. Showcasing local artists and hosting creative workshops.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2650,
        longitude: -97.7490,
        interests: ['art', 'painting', 'sculpture', 'culture'],
        account_type: 'business',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
      },
      {
        username: 'demo_user',
        email: 'demo@fluttrr.com',
        password_hash: 'demo1234',
        display_name: 'Demo User',
        bio: 'Just exploring Fluttrr! Love meeting new people and discovering cool events around town.',
        city: 'Austin',
        state: 'Texas',
        latitude: 30.2672,
        longitude: -97.7431,
        interests: ['coffee', 'trivia', 'live_music', 'food', 'fitness', 'art'],
        account_type: 'user',
        is_verified: true,
        avatar_url: '/api/placeholder/150/150',
        follower_count: 42,
        following_count: 67,
        events_attended_count: 15,
      },
    ], { individualHooks: true });

    logger.info(`Created ${users.length} users`);

    // ===== Create Businesses =====
    const businesses = await Business.bulkCreate([
      {
        owner_id: users[5].id,
        name: 'BrewHaus ATX',
        slug: 'brewhaus-atx',
        description: "Austin's premier craft brewery and taproom. We brew our own beers on-site and feature 24 rotating taps from local breweries. Our kitchen serves up elevated pub fare, and our event space hosts everything from trivia nights to live music. Come for the beer, stay for the community.",
        short_description: 'Craft brewery with 24 taps, great food, and amazing events',
        category: 'bar',
        logo_url: '/api/placeholder/200/200',
        cover_photo_url: '/api/placeholder/800/400',
        photos: ['/api/placeholder/600/400', '/api/placeholder/600/400', '/api/placeholder/600/400'],
        address: '1200 East 6th Street',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2672,
        longitude: -97.7431,
        phone: '(512) 555-0101',
        email: 'hello@brewhaus.com',
        website: 'https://brewhaus.example.com',
        social_links: { instagram: '@brewhausatx', facebook: 'brewhausatx', twitter: '@brewhausatx' },
        amenities: ['wifi', 'outdoor_seating', 'parking', 'pet_friendly', 'wheelchair_accessible', 'live_music'],
        tags: ['craft_beer', 'brewery', 'live_music', 'trivia', 'food'],
        price_range: '$$',
        rating: 4.7,
        review_count: 234,
        follower_count: 1250,
        total_events: 48,
        is_verified: true,
        is_featured: true,
      },
      {
        owner_id: users[6].id,
        name: 'Grindhouse Coffee',
        slug: 'grindhouse-coffee',
        description: 'More than just a coffee shop. Grindhouse is a community hub for remote workers, creatives, and coffee lovers. We source our beans directly from farms in Colombia and Ethiopia, and our baristas are true coffee artisans. With fast wifi, plenty of outlets, and a cozy atmosphere, this is your new office away from the office.',
        short_description: 'Specialty coffee shop and coworking space with the best beans in Austin',
        category: 'cafe',
        logo_url: '/api/placeholder/200/200',
        cover_photo_url: '/api/placeholder/800/400',
        photos: ['/api/placeholder/600/400', '/api/placeholder/600/400'],
        address: '456 South Congress Ave',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2500,
        longitude: -97.7500,
        phone: '(512) 555-0202',
        email: 'hello@grindhouse.com',
        website: 'https://grindhouse.example.com',
        social_links: { instagram: '@grindhousecoffee' },
        amenities: ['wifi', 'outlets', 'outdoor_seating', 'parking', 'wheelchair_accessible'],
        tags: ['coffee', 'coworking', 'remote_work', 'specialty_coffee'],
        price_range: '$',
        rating: 4.8,
        review_count: 189,
        follower_count: 890,
        total_events: 32,
        is_verified: true,
        is_featured: true,
      },
      {
        owner_id: users[7].id,
        name: 'Lucky Lanes Bowling',
        slug: 'lucky-lanes-bowling',
        description: 'Lucky Lanes is not your grandma\'s bowling alley (unless your grandma is really cool). We\'ve got 32 lanes, glow bowling on weekends, a full bar with craft cocktails, an arcade with 50+ games, and we host leagues, tournaments, and special events every week. It\'s where fun comes to party.',
        short_description: 'Retro bowling alley with glow bowling, arcade, and great events',
        category: 'bowling',
        logo_url: '/api/placeholder/200/200',
        cover_photo_url: '/api/placeholder/800/400',
        photos: ['/api/placeholder/600/400', '/api/placeholder/600/400', '/api/placeholder/600/400', '/api/placeholder/600/400'],
        address: '789 Lamar Blvd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78703',
        latitude: 30.2630,
        longitude: -97.7520,
        phone: '(512) 555-0303',
        email: 'hello@luckylanes.com',
        website: 'https://luckylanes.example.com',
        social_links: { instagram: '@luckylanesatx', tiktok: '@luckylanesatx' },
        amenities: ['parking', 'wheelchair_accessible', 'full_bar', 'arcade', 'food'],
        tags: ['bowling', 'arcade', 'entertainment', 'glow_bowling', 'leagues'],
        price_range: '$$',
        rating: 4.5,
        review_count: 312,
        follower_count: 760,
        total_events: 56,
        is_verified: true,
        is_featured: false,
      },
      {
        owner_id: users[8].id,
        name: 'Flow Yoga Studio',
        slug: 'flow-yoga-studio',
        description: 'Flow Yoga Studio is a welcoming space for yogis of all levels. We offer a variety of classes from gentle restorative sessions to challenging power flows. Our studio also hosts workshops, meditation sessions, and wellness events. Find your balance, find your community.',
        short_description: 'Community yoga studio for all levels with workshops and wellness events',
        category: 'gym',
        logo_url: '/api/placeholder/200/200',
        cover_photo_url: '/api/placeholder/800/400',
        photos: ['/api/placeholder/600/400', '/api/placeholder/600/400'],
        address: '321 Barton Springs Rd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2580,
        longitude: -97.7450,
        phone: '(512) 555-0404',
        email: 'namaste@flowyoga.com',
        website: 'https://flowyoga.example.com',
        social_links: { instagram: '@flowyogaatx' },
        amenities: ['parking', 'showers', 'mat_rental', 'water_station'],
        tags: ['yoga', 'wellness', 'meditation', 'fitness', 'community'],
        price_range: '$$',
        rating: 4.9,
        review_count: 156,
        follower_count: 620,
        total_events: 28,
        is_verified: true,
        is_featured: true,
      },
      {
        owner_id: users[9].id,
        name: 'Palette Art Gallery',
        slug: 'palette-art-gallery',
        description: 'Palette is a contemporary art gallery showcasing emerging and established local artists. We host rotating exhibitions, paint & sip nights, artist talks, and creative workshops. Art should be accessible to everyone, and that\'s exactly what we\'re about.',
        short_description: 'Contemporary art gallery with workshops, exhibitions, and creative events',
        category: 'gallery',
        logo_url: '/api/placeholder/200/200',
        cover_photo_url: '/api/placeholder/800/400',
        photos: ['/api/placeholder/600/400', '/api/placeholder/600/400', '/api/placeholder/600/400'],
        address: '567 East Cesar Chavez St',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2650,
        longitude: -97.7490,
        phone: '(512) 555-0505',
        email: 'info@palettegallery.com',
        website: 'https://palette.example.com',
        social_links: { instagram: '@paletteatx', facebook: 'paletteatx' },
        amenities: ['wifi', 'wheelchair_accessible', 'parking'],
        tags: ['art', 'gallery', 'painting', 'workshops', 'culture'],
        price_range: '$',
        rating: 4.6,
        review_count: 98,
        follower_count: 450,
        total_events: 24,
        is_verified: true,
        is_featured: false,
      },
    ]);

    logger.info(`Created ${businesses.length} businesses`);

    // ===== Create Events =====
    const now = new Date();
    const tomorrow = new Date(now.getTime() + 86400000);
    const dayAfter = new Date(now.getTime() + 2 * 86400000);
    const nextWeek = new Date(now.getTime() + 7 * 86400000);
    const in3Days = new Date(now.getTime() + 3 * 86400000);
    const in4Days = new Date(now.getTime() + 4 * 86400000);
    const in5Days = new Date(now.getTime() + 5 * 86400000);

    const events = await Event.bulkCreate([
      {
        business_id: businesses[0].id,
        created_by: users[5].id,
        title: 'Tuesday Trivia Night: Pop Culture Edition',
        slug: 'tuesday-trivia-pop-culture-' + Date.now().toString(36),
        description: 'Think you know your pop culture? Prove it! Our weekly trivia night is back with a Pop Culture theme. Form teams of up to 6, enjoy $5 pints all night, and compete for prizes including a $100 bar tab for the winning team. DJ spinning throwback hits between rounds. No cover, just good vibes and great beer.',
        short_description: 'Weekly trivia with $5 pints, prizes, and DJ sets between rounds',
        category: 'trivia',
        tags: ['trivia', 'pop_culture', 'beer', 'prizes', 'teams'],
        vibe_tags: ['social', 'competitive', 'casual', 'fun'],
        image_url: '/api/placeholder/800/500',
        gallery: ['/api/placeholder/600/400', '/api/placeholder/600/400'],
        start_time: new Date(tomorrow.setHours(19, 0, 0, 0)),
        end_time: new Date(tomorrow.setHours(22, 0, 0, 0)),
        venue_name: 'BrewHaus ATX',
        address: '1200 East 6th Street',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2672,
        longitude: -97.7431,
        price: 0,
        is_free: true,
        max_attendees: 120,
        attendee_count: 67,
        interested_count: 34,
        view_count: 450,
        share_count: 23,
        age_restriction: '21+',
        difficulty_level: 'all_levels',
        status: 'published',
        is_featured: true,
        accessibility: { wheelchair: true, parking: true, public_transit: true },
      },
      {
        business_id: businesses[1].id,
        created_by: users[6].id,
        title: 'Remote Work Wednesday - Free Coworking Day',
        slug: 'remote-work-wednesday-' + Date.now().toString(36),
        description: 'Tired of working from your couch? Join us every Wednesday for Remote Work Day! Get a free coffee with any food purchase, enjoy our fast wifi, plenty of outlets, and meet other remote workers. We set up community tables for networking and have a \"coffee break\" at 2pm where everyone takes 15 minutes to chat and connect.',
        short_description: 'Free coworking with coffee, wifi, and networking breaks',
        category: 'networking',
        tags: ['coworking', 'remote_work', 'networking', 'coffee', 'wifi'],
        vibe_tags: ['productive', 'chill', 'social', 'professional'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(dayAfter.setHours(8, 0, 0, 0)),
        end_time: new Date(dayAfter.setHours(17, 0, 0, 0)),
        venue_name: 'Grindhouse Coffee',
        address: '456 South Congress Ave',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2500,
        longitude: -97.7500,
        price: 0,
        is_free: true,
        max_attendees: 40,
        attendee_count: 28,
        interested_count: 15,
        view_count: 320,
        age_restriction: 'all_ages',
        difficulty_level: 'all_levels',
        status: 'published',
        is_featured: true,
        what_to_bring: ['laptop', 'charger', 'headphones'],
      },
      {
        business_id: businesses[2].id,
        created_by: users[7].id,
        title: 'Glow Bowl Friday: Cosmic Bowling Night',
        slug: 'glow-bowl-friday-' + Date.now().toString(36),
        description: 'The lights go down, the UV comes up, and the party starts! Our Glow Bowl Friday features cosmic bowling with black lights, fog machines, and a live DJ spinning club hits. $15 gets you 2 hours of bowling and shoe rental. Drink specials all night. Grab your crew and glow up!',
        short_description: 'Cosmic bowling with UV lights, DJ, and drink specials',
        category: 'themed_night',
        tags: ['bowling', 'glow', 'cosmic', 'dj', 'drinks'],
        vibe_tags: ['party', 'energetic', 'fun', 'social'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in3Days.setHours(20, 0, 0, 0)),
        end_time: new Date(in3Days.setHours(23, 59, 0, 0)),
        venue_name: 'Lucky Lanes Bowling',
        address: '789 Lamar Blvd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78703',
        latitude: 30.2630,
        longitude: -97.7520,
        price: 15.00,
        is_free: false,
        price_description: '$15 includes 2 hours bowling + shoe rental',
        max_attendees: 200,
        attendee_count: 145,
        interested_count: 56,
        view_count: 890,
        share_count: 45,
        age_restriction: 'all_ages',
        status: 'published',
        is_featured: true,
      },
      {
        business_id: businesses[3].id,
        created_by: users[8].id,
        title: 'Sunrise Yoga in the Park',
        slug: 'sunrise-yoga-park-' + Date.now().toString(36),
        description: 'Start your morning right with our outdoor sunrise yoga session at Zilker Park. This gentle flow class is suitable for all levels and will leave you feeling centered and energized for the day. Free for all! Just bring a mat and water. We\'ll provide the good vibes and the stunning Austin sunrise.',
        short_description: 'Free outdoor yoga at Zilker Park for all levels',
        category: 'fitness',
        tags: ['yoga', 'sunrise', 'outdoor', 'wellness', 'free'],
        vibe_tags: ['peaceful', 'energizing', 'welcoming', 'healthy'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(tomorrow.setHours(6, 30, 0, 0)),
        end_time: new Date(tomorrow.setHours(7, 45, 0, 0)),
        venue_name: 'Zilker Park (near Barton Springs entrance)',
        address: 'Zilker Park, Barton Springs Rd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2669,
        longitude: -97.7710,
        price: 0,
        is_free: true,
        max_attendees: 50,
        attendee_count: 32,
        interested_count: 20,
        view_count: 280,
        age_restriction: 'all_ages',
        difficulty_level: 'beginner',
        status: 'published',
        is_featured: false,
        what_to_bring: ['yoga_mat', 'water_bottle', 'towel'],
        accessibility: { wheelchair: false, parking: true, public_transit: true },
      },
      {
        business_id: businesses[4].id,
        created_by: users[9].id,
        title: 'Paint & Sip: Austin Skyline at Sunset',
        slug: 'paint-sip-austin-skyline-' + Date.now().toString(36),
        description: 'No experience needed! Join us for a guided painting session where you\'ll create your own Austin skyline sunset masterpiece. Includes all art supplies, a glass of wine or beer, and expert instruction from local artist Maria Gonzalez. Take home your finished painting at the end of the night!',
        short_description: 'Guided painting with wine, all supplies included',
        category: 'art',
        tags: ['painting', 'wine', 'art', 'guided', 'creative'],
        vibe_tags: ['creative', 'relaxing', 'social', 'date_night'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in4Days.setHours(18, 30, 0, 0)),
        end_time: new Date(in4Days.setHours(21, 0, 0, 0)),
        venue_name: 'Palette Art Gallery',
        address: '567 East Cesar Chavez St',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2650,
        longitude: -97.7490,
        price: 35.00,
        is_free: false,
        price_description: '$35 includes all supplies + 1 drink',
        max_attendees: 30,
        attendee_count: 24,
        interested_count: 12,
        view_count: 520,
        share_count: 18,
        age_restriction: '21+',
        difficulty_level: 'beginner',
        status: 'published',
        is_featured: true,
      },
      {
        business_id: businesses[0].id,
        created_by: users[5].id,
        title: 'Live Music Saturday: The Wayward Souls',
        slug: 'live-music-wayward-souls-' + Date.now().toString(36),
        description: 'Austin\'s hottest indie folk band The Wayward Souls are playing a special acoustic set at BrewHaus! No cover charge. Grab a seat on our patio, order some craft brews, and enjoy an amazing night of live music under the stars. Doors open at 7, music starts at 8.',
        short_description: 'Free acoustic set by The Wayward Souls on the patio',
        category: 'music',
        tags: ['live_music', 'indie_folk', 'acoustic', 'free', 'patio'],
        vibe_tags: ['chill', 'social', 'romantic', 'artsy'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in5Days.setHours(19, 0, 0, 0)),
        end_time: new Date(in5Days.setHours(22, 30, 0, 0)),
        venue_name: 'BrewHaus ATX - Patio Stage',
        address: '1200 East 6th Street',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2672,
        longitude: -97.7431,
        price: 0,
        is_free: true,
        max_attendees: 150,
        attendee_count: 89,
        interested_count: 45,
        view_count: 670,
        share_count: 32,
        age_restriction: '21+',
        status: 'published',
        is_featured: false,
      },
      {
        business_id: businesses[1].id,
        created_by: users[6].id,
        title: 'Board Game Brunch',
        slug: 'board-game-brunch-' + Date.now().toString(36),
        description: 'Grab a coffee, a pastry, and a seat at one of our game tables! We\'ve got over 100 board games available, from classics like Settlers of Catan to new hits. Come solo and join a table or bring your friends. Our baristas will keep the coffee flowing. Games are free to play with any purchase.',
        short_description: 'Coffee, pastries, and 100+ board games to play',
        category: 'board_games',
        tags: ['board_games', 'brunch', 'coffee', 'social', 'games'],
        vibe_tags: ['casual', 'fun', 'social', 'geeky'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(nextWeek.setHours(10, 0, 0, 0)),
        end_time: new Date(nextWeek.setHours(14, 0, 0, 0)),
        venue_name: 'Grindhouse Coffee',
        address: '456 South Congress Ave',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2500,
        longitude: -97.7500,
        price: 0,
        is_free: true,
        max_attendees: 35,
        attendee_count: 18,
        interested_count: 22,
        view_count: 240,
        age_restriction: 'all_ages',
        difficulty_level: 'all_levels',
        status: 'published',
        is_featured: false,
      },
      {
        business_id: businesses[2].id,
        created_by: users[7].id,
        title: 'Beginner Bowling League - Season 2',
        slug: 'beginner-bowling-league-s2-' + Date.now().toString(36),
        description: 'Never bowled competitively? No problem! Our beginner league is designed for people who want to have fun and improve their game in a no-pressure environment. 8-week season, teams of 4, with weekly prizes and an end-of-season tournament. Meet new friends while learning to bowl!',
        short_description: '8-week beginner bowling league, teams of 4, weekly prizes',
        category: 'sports',
        tags: ['bowling', 'league', 'beginner', 'teams', 'competitive'],
        vibe_tags: ['competitive', 'social', 'fun', 'sporty'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(nextWeek.setHours(18, 30, 0, 0)),
        end_time: new Date(nextWeek.setHours(21, 0, 0, 0)),
        venue_name: 'Lucky Lanes Bowling',
        address: '789 Lamar Blvd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78703',
        latitude: 30.2630,
        longitude: -97.7520,
        price: 20.00,
        is_free: false,
        price_description: '$20/week includes shoe rental and 3 games',
        max_attendees: 48,
        attendee_count: 36,
        interested_count: 15,
        view_count: 380,
        age_restriction: 'all_ages',
        difficulty_level: 'beginner',
        status: 'published',
        is_featured: false,
        recurrence: { type: 'weekly', day: 'wednesday', duration_weeks: 8 },
      },
      {
        business_id: businesses[3].id,
        created_by: users[8].id,
        title: 'Sound Bath Meditation Experience',
        slug: 'sound-bath-meditation-' + Date.now().toString(36),
        description: 'Immerse yourself in the healing vibrations of crystal singing bowls, gongs, and chimes. Our Sound Bath Meditation is a deeply relaxing experience that helps reduce stress, improve sleep, and promote overall wellbeing. No meditation experience needed. Just lie down, close your eyes, and let the sound wash over you.',
        short_description: 'Crystal singing bowl meditation for deep relaxation',
        category: 'wellness',
        tags: ['meditation', 'sound_bath', 'wellness', 'relaxation', 'healing'],
        vibe_tags: ['peaceful', 'healing', 'spiritual', 'calming'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in4Days.setHours(19, 30, 0, 0)),
        end_time: new Date(in4Days.setHours(21, 0, 0, 0)),
        venue_name: 'Flow Yoga Studio',
        address: '321 Barton Springs Rd',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2580,
        longitude: -97.7450,
        price: 25.00,
        is_free: false,
        price_description: '$25 per person',
        max_attendees: 25,
        attendee_count: 20,
        interested_count: 10,
        view_count: 310,
        age_restriction: 'all_ages',
        difficulty_level: 'beginner',
        status: 'published',
        is_featured: false,
        what_to_bring: ['yoga_mat', 'blanket', 'pillow'],
      },
      {
        business_id: businesses[0].id,
        created_by: users[5].id,
        title: 'Salsa Night: Beginner Lesson + Social Dance',
        slug: 'salsa-night-beginner-' + Date.now().toString(36),
        description: 'Always wanted to learn salsa? Here\'s your chance! We start with a 45-minute beginner lesson taught by professional dance instructor Luna Martinez, followed by open social dancing until midnight. No partner needed - we rotate partners during the lesson. $5 cover includes the lesson. Drink specials all night!',
        short_description: 'Beginner salsa lesson + open social dancing with drink specials',
        category: 'dance',
        tags: ['salsa', 'dance', 'beginner', 'social_dancing', 'latin'],
        vibe_tags: ['energetic', 'social', 'romantic', 'fun'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in3Days.setHours(20, 0, 0, 0)),
        end_time: new Date(in3Days.setHours(23, 59, 0, 0)),
        venue_name: 'BrewHaus ATX',
        address: '1200 East 6th Street',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2672,
        longitude: -97.7431,
        price: 5.00,
        is_free: false,
        price_description: '$5 cover includes beginner lesson',
        max_attendees: 80,
        attendee_count: 52,
        interested_count: 30,
        view_count: 560,
        share_count: 28,
        age_restriction: '21+',
        difficulty_level: 'beginner',
        status: 'published',
        is_featured: true,
      },
      {
        business_id: businesses[4].id,
        created_by: users[9].id,
        title: 'First Friday Art Walk & Exhibition Opening',
        slug: 'first-friday-art-walk-' + Date.now().toString(36),
        description: 'Join us for our monthly First Friday Art Walk featuring a new exhibition by three emerging Austin artists. Free admission, complimentary wine and cheese, and live ambient music. Meet the artists, explore the gallery, and discover your next favorite piece. Art prints available starting at $50.',
        short_description: 'Monthly art walk with new exhibition, free wine, and live music',
        category: 'art',
        tags: ['art_walk', 'exhibition', 'gallery', 'wine', 'free'],
        vibe_tags: ['artsy', 'cultural', 'social', 'sophisticated'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in5Days.setHours(18, 0, 0, 0)),
        end_time: new Date(in5Days.setHours(21, 0, 0, 0)),
        venue_name: 'Palette Art Gallery',
        address: '567 East Cesar Chavez St',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78702',
        latitude: 30.2650,
        longitude: -97.7490,
        price: 0,
        is_free: true,
        max_attendees: 100,
        attendee_count: 45,
        interested_count: 38,
        view_count: 420,
        share_count: 22,
        age_restriction: 'all_ages',
        status: 'published',
        is_featured: false,
      },
      {
        business_id: businesses[1].id,
        created_by: users[6].id,
        title: 'Open Mic Night: Poetry & Acoustic',
        slug: 'open-mic-poetry-acoustic-' + Date.now().toString(36),
        description: 'Got something to share? Our monthly Open Mic Night welcomes poets, singer-songwriters, and spoken word artists. Sign up starts at 6:30, performances begin at 7. Each performer gets 10 minutes. Free entry, and all performers get a free coffee. Come support local creatives!',
        short_description: 'Monthly open mic for poets and musicians, free entry',
        category: 'open_mic',
        tags: ['open_mic', 'poetry', 'acoustic', 'music', 'spoken_word'],
        vibe_tags: ['creative', 'intimate', 'supportive', 'artsy'],
        image_url: '/api/placeholder/800/500',
        start_time: new Date(in4Days.setHours(18, 30, 0, 0)),
        end_time: new Date(in4Days.setHours(21, 30, 0, 0)),
        venue_name: 'Grindhouse Coffee',
        address: '456 South Congress Ave',
        city: 'Austin',
        state: 'Texas',
        zip_code: '78704',
        latitude: 30.2500,
        longitude: -97.7500,
        price: 0,
        is_free: true,
        max_attendees: 60,
        attendee_count: 35,
        interested_count: 20,
        view_count: 290,
        age_restriction: 'all_ages',
        difficulty_level: 'all_levels',
        status: 'published',
        is_featured: false,
      },
    ]);

    logger.info(`Created ${events.length} events`);

    // ===== Create Event Attendees =====
    const demoUser = users[10]; // demo_user
    const attendees = await EventAttendee.bulkCreate([
      { event_id: events[0].id, user_id: users[0].id, status: 'going', source: 'discover' },
      { event_id: events[0].id, user_id: users[3].id, status: 'going', source: 'discover' },
      { event_id: events[0].id, user_id: demoUser.id, status: 'going', source: 'discover' },
      { event_id: events[1].id, user_id: users[0].id, status: 'going', source: 'direct' },
      { event_id: events[1].id, user_id: users[3].id, status: 'going', source: 'discover' },
      { event_id: events[1].id, user_id: demoUser.id, status: 'interested', source: 'discover' },
      { event_id: events[2].id, user_id: users[1].id, status: 'going', source: 'discover' },
      { event_id: events[2].id, user_id: users[4].id, status: 'going', source: 'invite' },
      { event_id: events[3].id, user_id: users[2].id, status: 'going', source: 'discover' },
      { event_id: events[3].id, user_id: users[4].id, status: 'going', source: 'direct' },
      { event_id: events[3].id, user_id: demoUser.id, status: 'going', source: 'discover' },
      { event_id: events[4].id, user_id: users[2].id, status: 'going', source: 'discover' },
      { event_id: events[4].id, user_id: users[0].id, status: 'interested', source: 'discover' },
      { event_id: events[5].id, user_id: users[1].id, status: 'going', source: 'discover' },
      { event_id: events[5].id, user_id: demoUser.id, status: 'going', source: 'discover' },
      { event_id: events[6].id, user_id: users[0].id, status: 'going', source: 'discover' },
      { event_id: events[6].id, user_id: users[3].id, status: 'going', source: 'discover' },
      { event_id: events[9].id, user_id: users[4].id, status: 'going', source: 'direct' },
      { event_id: events[9].id, user_id: demoUser.id, status: 'interested', source: 'discover' },
    ]);

    logger.info(`Created ${attendees.length} event attendees`);

    // ===== Create Chat Rooms =====
    const chatRooms = await ChatRoom.bulkCreate([
      {
        name: 'Tuesday Trivia Night Chat',
        type: 'event',
        event_id: events[0].id,
        created_by: users[5].id,
        member_count: 4,
        description: 'Chat for trivia night attendees!',
        is_active: true,
        last_message: { content: 'Can\'t wait for tomorrow! Anyone need a team?', sender_name: 'Sarah Chen' },
        last_message_at: new Date(now.getTime() - 3600000),
      },
      {
        name: 'Remote Work Wednesday',
        type: 'event',
        event_id: events[1].id,
        created_by: users[6].id,
        member_count: 3,
        description: 'Coordinate and chat about coworking sessions',
        is_active: true,
        last_message: { content: 'I\'ll be there early to grab the corner table!', sender_name: 'James Park' },
        last_message_at: new Date(now.getTime() - 7200000),
      },
      {
        name: null,
        type: 'direct',
        created_by: demoUser.id,
        member_count: 2,
        is_active: true,
        last_message: { content: 'Hey! Are you going to trivia night?', sender_name: 'Demo User' },
        last_message_at: new Date(now.getTime() - 1800000),
      },
      {
        name: 'Glow Bowl Friday',
        type: 'event',
        event_id: events[2].id,
        created_by: users[7].id,
        member_count: 3,
        is_active: true,
        last_message: { content: 'Who wants to be on my team?!', sender_name: 'Mike Rodriguez' },
        last_message_at: new Date(now.getTime() - 5400000),
      },
      {
        name: 'BrewHaus Community',
        type: 'business',
        business_id: businesses[0].id,
        created_by: users[5].id,
        member_count: 6,
        description: 'Official BrewHaus ATX community chat',
        is_active: true,
        last_message: { content: 'New seasonal IPA dropping next week!', sender_name: 'BrewHaus ATX' },
        last_message_at: new Date(now.getTime() - 900000),
      },
    ]);

    logger.info(`Created ${chatRooms.length} chat rooms`);

    // ===== Create Chat Members =====
    await ChatMember.bulkCreate([
      { room_id: chatRooms[0].id, user_id: users[5].id, role: 'owner' },
      { room_id: chatRooms[0].id, user_id: users[0].id, role: 'member' },
      { room_id: chatRooms[0].id, user_id: users[3].id, role: 'member' },
      { room_id: chatRooms[0].id, user_id: demoUser.id, role: 'member', unread_count: 3 },
      { room_id: chatRooms[1].id, user_id: users[6].id, role: 'owner' },
      { room_id: chatRooms[1].id, user_id: users[0].id, role: 'member' },
      { room_id: chatRooms[1].id, user_id: users[3].id, role: 'member' },
      { room_id: chatRooms[2].id, user_id: demoUser.id, role: 'member' },
      { room_id: chatRooms[2].id, user_id: users[0].id, role: 'member', unread_count: 1 },
      { room_id: chatRooms[3].id, user_id: users[7].id, role: 'owner' },
      { room_id: chatRooms[3].id, user_id: users[1].id, role: 'member' },
      { room_id: chatRooms[3].id, user_id: users[4].id, role: 'member' },
      { room_id: chatRooms[4].id, user_id: users[5].id, role: 'owner' },
      { room_id: chatRooms[4].id, user_id: users[0].id, role: 'member' },
      { room_id: chatRooms[4].id, user_id: users[1].id, role: 'member' },
      { room_id: chatRooms[4].id, user_id: users[3].id, role: 'member' },
      { room_id: chatRooms[4].id, user_id: demoUser.id, role: 'member', unread_count: 5 },
      { room_id: chatRooms[4].id, user_id: users[2].id, role: 'member' },
    ]);

    logger.info('Created chat members');

    // ===== Create Follows =====
    await Follow.bulkCreate([
      { follower_id: demoUser.id, following_id: users[0].id, type: 'user' },
      { follower_id: demoUser.id, following_id: users[1].id, type: 'user' },
      { follower_id: demoUser.id, following_id: users[4].id, type: 'user' },
      { follower_id: demoUser.id, business_id: businesses[0].id, type: 'business' },
      { follower_id: demoUser.id, business_id: businesses[1].id, type: 'business' },
      { follower_id: demoUser.id, business_id: businesses[3].id, type: 'business' },
      { follower_id: users[0].id, following_id: demoUser.id, type: 'user' },
      { follower_id: users[1].id, following_id: demoUser.id, type: 'user' },
      { follower_id: users[3].id, following_id: demoUser.id, type: 'user' },
      { follower_id: users[0].id, business_id: businesses[0].id, type: 'business' },
      { follower_id: users[0].id, business_id: businesses[1].id, type: 'business' },
      { follower_id: users[1].id, business_id: businesses[0].id, type: 'business' },
      { follower_id: users[1].id, business_id: businesses[2].id, type: 'business' },
      { follower_id: users[2].id, business_id: businesses[3].id, type: 'business' },
      { follower_id: users[2].id, business_id: businesses[4].id, type: 'business' },
    ]);

    logger.info('Created follows');

    // ===== Create Saved Events =====
    await SavedEvent.bulkCreate([
      { user_id: demoUser.id, event_id: events[4].id, collection: 'default' },
      { user_id: demoUser.id, event_id: events[6].id, collection: 'default' },
      { user_id: demoUser.id, event_id: events[9].id, collection: 'date_ideas' },
      { user_id: users[0].id, event_id: events[0].id, collection: 'default' },
      { user_id: users[0].id, event_id: events[5].id, collection: 'default' },
    ]);

    logger.info('Created saved events');

    // ===== Create Reviews =====
    await Review.bulkCreate([
      {
        user_id: users[0].id,
        business_id: businesses[0].id,
        event_id: events[0].id,
        rating: 5,
        title: 'Best trivia night in Austin!',
        content: 'The trivia questions are challenging but fun, the beer selection is amazing, and the atmosphere is perfect. Our team had an absolute blast!',
        is_verified_attendance: true,
      },
      {
        user_id: users[1].id,
        business_id: businesses[2].id,
        rating: 4,
        title: 'Great bowling, great vibes',
        content: 'Love the glow bowling nights! The DJ is always on point. Only wish the food menu had more options.',
        is_verified_attendance: true,
      },
      {
        user_id: users[2].id,
        business_id: businesses[3].id,
        rating: 5,
        title: 'My happy place',
        content: 'The instructors are amazing and the community is so welcoming. The sunrise yoga in the park was a magical experience.',
        is_verified_attendance: true,
      },
      {
        user_id: demoUser.id,
        business_id: businesses[0].id,
        rating: 5,
        title: 'Amazing atmosphere and events',
        content: 'BrewHaus never disappoints. Great beer, great events, and the staff is super friendly. Trivia night is a must!',
        is_verified_attendance: true,
      },
      {
        user_id: users[3].id,
        business_id: businesses[1].id,
        rating: 5,
        title: 'Perfect workspace',
        content: 'Best coffee shop for remote work in Austin. Fast wifi, great coffee, and the coworking days are such a good idea.',
        is_verified_attendance: true,
      },
    ]);

    logger.info('Created reviews');

    // ===== Create Notifications =====
    await Notification.bulkCreate([
      {
        user_id: demoUser.id,
        sender_id: users[5].id,
        type: 'event_reminder',
        title: 'Trivia Night Tomorrow!',
        body: 'Tuesday Trivia Night: Pop Culture Edition starts tomorrow at 7 PM. Don\'t forget to bring your team!',
        data: { event_id: events[0].id },
        action_url: `/events/${events[0].id}`,
      },
      {
        user_id: demoUser.id,
        sender_id: users[0].id,
        type: 'new_follower',
        title: 'New Follower',
        body: 'Sarah Chen started following you',
        data: { user_id: users[0].id },
        action_url: `/users/${users[0].id}`,
      },
      {
        user_id: demoUser.id,
        type: 'event_nearby',
        title: 'New Event Nearby',
        body: 'Glow Bowl Friday is happening at Lucky Lanes Bowling, just 0.5 miles away!',
        data: { event_id: events[2].id },
        action_url: `/events/${events[2].id}`,
      },
      {
        user_id: demoUser.id,
        sender_id: users[6].id,
        type: 'business_update',
        title: 'Grindhouse Coffee Posted a New Event',
        body: 'Board Game Brunch is coming up next week! Free to play with any purchase.',
        data: { event_id: events[6].id, business_id: businesses[1].id },
        action_url: `/events/${events[6].id}`,
        is_read: true,
      },
    ]);

    logger.info('Created notifications');

    logger.info('Database seeded successfully!');
    logger.info(`
    ====================================
    Demo Login Credentials:
    Email: demo@fluttrr.com
    Password: demo1234
    ====================================
    `);

    process.exit(0);
  } catch (error) {
    logger.error('Seed failed:', error);
    process.exit(1);
  }
};

seed();
